# Generated by Django 5.0.3 on 2024-03-28 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
    ]
